name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0

  firebase_messaging: ^6.0.16
  firebase_core: ^0.4.5
  firebase_analytics: ^1.0.4
  cloud_firestore: ^0.13.6
  http: ^0.12.0
  intl: ^0.16.1
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
